spring.config.import=optional:file:.env[.properties]
spring.application.name=hotelmanagementapi
server.port=${PORT:8443}

spring.datasource.driver-class-name=${DATASOURCE_DRIVER_CLASS_NAME_I}
spring.datasource.url=${DATASOURCE_URL_I}
spring.datasource.username=${DATASOURCE_USERNAME_I}
spring.datasource.password=${DATASOURCE_PASSWORD_I}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true





JWT_SECRET_KEY=${JWT_SECRET_KEY_I}
JWT_SECRET_ACCESS_KEY_EXPIRATION=${JWT_SECRET_ACCESS_KEY_EXPIRATION_I}
JWT_SECRET_REFRESH_KEY_EXPIRATION=${JWT_SECRET_REFRESH_KEY_EXPIRATION_I}
CORS_Origin=${CORS_Origin_I}



