spring.config.import=optional:file:.env[.properties]
spring.application.name=hotelmanagementapi
server.port=8443

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/playground
spring.datasource.username=Ash
spring.datasource.password=Ash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#ssl
spring.ssl.bundle.jks.hotelmanagementsecuritybundle.keystore.location=classpath:hotelmanagement_keystore.p12
spring.ssl.bundle.jks.hotelmanagementsecuritybundle.keystore.password=hotelmanagement_key
spring.ssl.bundle.jks.hotelmanagementsecuritybundle.keystore.type=PKCS12
server.ssl.bundle=hotelmanagementsecuritybundle



